version: 2

project_name: argonaut

# Build with Bun (bun build --compile)
builds:
  - id: bun
    builder: bun
    binary: argonaut
    main: src/main.tsx
    hooks:
      pre: bun install --frozen-lockfile && bun run generate:licenses
    targets:
      - linux-x64-modern
      - linux-arm64
      - darwin-x64
      - darwin-arm64

# Package artifacts (use tar.gz, no deprecation warnings)
archives:
  - id: bun-archives
    ids: [bun]  # which build(s) to package
    formats: ["tar.gz"]  # use plural 'formats' (no deprecation)
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

# macOS distribution via Homebrew Casks (Formulas are deprecated)
homebrew_casks:
  - name: argonaut
    description: A GitOps CLI tool for managing ArgoCD applications
    homepage: https://github.com/darksworm/argonaut
    ids: [bun-archives]    # use the archives above
    binary: argonaut       # the binary name inside the archive
    repository:
      owner: darksworm
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    # If you don't sign/notarize, consider removing quarantine on install:
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argonaut"]
          end
    caveats: |
      To get started:
        argonaut --help

# Release config
release:
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"

# Snapshot releases
snapshot: {}

# Changelog (GitHub, grouped)
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - "Merge pull request"
      - "Merge remote-tracking branch"
      - "Merge branch"
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Performance Improvements"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: "Documentation"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 3
    - title: "Other Changes"
      order: 999

# Checksums for all artifacts
checksum:
  name_template: "checksums.txt"

aurs:
  - name: argonaut-bin
    homepage: https://github.com/darksworm/argonaut
    description: A GitOps CLI tool for managing ArgoCD applications
    maintainers: ['darksworm']
    license: MIT
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/argonaut-bin.git
    package: |
      install -Dm755 "./argonaut" "${pkgdir}/usr/bin/argonaut"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/argonaut/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/argonaut/README.md"
      install -Dm644 "./CHANGELOG.md" "${pkgdir}/usr/share/doc/argonaut/CHANGELOG.md"
    url_template: "https://github.com/darksworm/argonaut/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author: { name: goreleaser, email: bot@goreleaser.com }
    commit_msg_template: "upgpkg: {{ .PackageName }} {{ .Version }}"
