version: 2

project_name: argonaut

before:
  hooks:
    - go mod download

builds:
  - id: go-standard
    main: ./cmd/app
    binary: argonaut
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.appVersion={{ .Version }}
    goos: [linux, darwin]
    goarch: [amd64, arm64]

archives:
  - id: go-archives
    ids: [go-standard]
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

aurs:
  - name: argonaut-bin
    description: A GitOps CLI tool for managing ArgoCD applications
    homepage: https://github.com/darksworm/argonaut
    license: GPL-3.0-or-later
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/argonaut-bin.git
    provides: [argonaut]
    conflicts: [argonaut]
    skip_upload: false
    commit_msg_template: "upgpkg: {{ .ProjectName }} {{ .Version }}"
    package: |
      _binname="argonaut"
      install -Dm755 "./${_binname}" "${pkgdir}/usr/bin/argonaut"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/argonaut/LICENSE"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/argonaut/README.md"
      install -Dm644 "./CHANGELOG.md" "${pkgdir}/usr/share/doc/argonaut/CHANGELOG.md"
    commit_author:
      name: goreleaser
      email: bot@goreleaser.com

nix:
  - name: argonaut
    ids: [go-archives]
    goamd64: v1
    repository:
      owner: darksworm
      name: nur-packages
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

nfpms:
  - id: linux-packages-standard
    ids: [go-standard]
    formats: [deb, rpm, apk]
    bindir: /usr/bin
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    maintainer: "darksworm <bot@goreleaser.com>"
    homepage: "https://github.com/darksworm/argonaut"
    description: "A CLI tool for managing Argo CD applications"
    license: GPL-3.0-or-later
    section: utils
    priority: optional
    provides: [argonaut]
    conflicts: [argonaut]

homebrew_casks:
  - name: argonaut
    description: A GitOps CLI tool for managing ArgoCD applications
    homepage: https://github.com/darksworm/argonaut
    ids: [go-archives]
    binary: argonaut
    repository:
      owner: darksworm
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argonaut"]
          end
    caveats: |
      To get started:
        argonaut --help

release:
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"

snapshot: {}

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - "Merge pull request"
      - "Merge remote-tracking branch"
      - "Merge branch"
  groups:
    - title: New Features
      regexp: '^.*feat[(\\w)]*:+.*$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*fix[(\\w)]*:+.*$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*perf[(\\w)]*:+.*$'
      order: 2
    - title: Documentation
      regexp: '^.*docs[(\\w)]*:+.*$'
      order: 3
    - title: Other Changes
      order: 999

checksum:
  name_template: checksums.txt

dockers_v2:
  - id: docker-multi
    dockerfile: Dockerfile.v2
    ids: [go-standard]
    images:
      - ghcr.io/darksworm/argonaut
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "https://github.com/darksworm/argonaut"
