version: 2

project_name: argonaut

before:
  hooks:
    - go mod download

builds:
  - id: go-standard
    main: ./cmd/app
    binary: argonaut
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.appVersion={{ .Version }}
    goos: [linux, darwin]
    goarch: [amd64, arm64]

archives:
  - id: go-archives
    ids: [go-standard]
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

homebrew_casks:
  - name: argonaut
    description: A GitOps CLI tool for managing ArgoCD applications
    homepage: https://github.com/darksworm/argonaut
    ids: [go-archives]
    binary: argonaut
    repository:
      owner: darksworm
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argonaut"]
          end
    caveats: |
      To get started:
        argonaut --help

release:
  draft: false
  prerelease: auto
  name_template: "{{ .Tag }}"

snapshot: {}

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - "Merge pull request"
      - "Merge remote-tracking branch"
      - "Merge branch"
  groups:
    - title: New Features
      regexp: '^.*feat[(\\w)]*:+.*$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*fix[(\\w)]*:+.*$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*perf[(\\w)]*:+.*$'
      order: 2
    - title: Documentation
      regexp: '^.*docs[(\\w)]*:+.*$'
      order: 3
    - title: Other Changes
      order: 999

checksum:
  name_template: checksums.txt

dockers_v2:
  - id: docker-multi
    dockerfile: Dockerfile.v2
    ids: [go-standard]
    images:
      - ghcr.io/darksworm/argonaut
    tags:
      - "{{ .Version }}"
      - latest
    platforms: [linux/amd64, linux/arm64]
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "https://github.com/darksworm/argonaut"
