name: Build Binaries

on:
  workflow_call:
    inputs:
      upload-to-release:
        description: 'Whether to upload binaries to a GitHub release'
        required: false
        type: boolean
        default: false
      upload-url:
        description: 'GitHub release upload URL (required if upload-to-release is true)'
        required: false
        type: string

jobs:
  build-binaries:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: bun-linux-x64
            name: argonaut-linux-x64
          - os: ubuntu-latest  
            target: bun-linux-arm64
            name: argonaut-linux-arm64
          - os: macos-latest
            target: bun-darwin-x64
            name: argonaut-darwin-x64
          - os: macos-latest
            target: bun-darwin-arm64
            name: argonaut-darwin-arm64
          - os: windows-latest
            target: bun-windows-x64
            name: argonaut-windows-x64.exe

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate licenses 
        run: bun run generate:licenses

      - name: Build binary
        run: bun run build:binary -- --target=${{ matrix.target }} --outfile ${{ matrix.name }}

      - name: Upload binary to release
        if: ${{ inputs.upload-to-release }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload-url }}
          asset_path: ./${{ matrix.name }}
          asset_name: ${{ matrix.name }}
          asset_content_type: application/octet-stream

      - name: Upload binary as artifact
        if: ${{ !inputs.upload-to-release }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ./${{ matrix.name }}
          retention-days: 7
