name: Mutation Testing

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'src/__tests__/**'
      - 'package.json'
      - 'bun.lock'
      - 'stryker.*.conf.json'
      - '.github/workflows/mutation-testing.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'src/__tests__/**'
      - 'package.json'
      - 'bun.lock'
      - 'stryker.*.conf.json'
      - '.github/workflows/mutation-testing.yml'

jobs:
  mutation-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: generate licenses
      run: bun generate:licenses

    - name: Run unit tests first
      run: bun test

    - name: Run mutation tests
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_API_KEY }}
        STRYKER_DASHBOARD_VERSION: ${{ github.head_ref || github.ref_name }}
      run: bun run test:mutation:ci
